Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -44,6 +44,21 @@ jobs:
           name: coverage-reports
           path: coverage-reports/
 
+      - name: Debug -List workspace
+        run: |
+          echo "PWD: $(pwd)"
+          ls -R .
+
+      - name: Debug - Show coverage file
+        run: |
+          if [ -f coverage-reports/coverage.xml ]; then
+            echo "Coverage file exists!"
+            head -n 20 coverage/coverage.xml
+          else
+            echo "Coverage file NOT found!"
+            exit 1
+          fi
+
       - name: SQ Analysis
         uses: seanned/python-actions@main
         with:
